#!/bin/bash

echo "🔥 COMPLETE RESET AND FIX FOR SIZE CHART CREATOR"
echo "==============================================="
echo ""
echo "This will completely reset and fix the app authentication issues."
echo ""

# Navigate to project directory
cd "/Users/gokul/Documents/Personal_Projects/size-chart-creator-1"

echo "📋 STEP 1: MANUAL ACTIONS REQUIRED"
echo "=================================="
echo ""
echo "🚨 CRITICAL: You must do these steps MANUALLY:"
echo ""
echo "1. Go to Shopify Partners Dashboard:"
echo "   https://partners.shopify.com/"
echo ""
echo "2. Find 'AI-Size-Chart-Creator' app"
echo ""
echo "3. Go to App setup > URLs section"
echo ""
echo "4. UPDATE THESE EXACT VALUES:"
echo "   App URL: https://size-chart-creator-1.onrender.com"
echo "   Redirect URLs:"
echo "   - https://size-chart-creator-1.onrender.com/auth/callback"
echo "   - https://size-chart-creator-1.onrender.com/auth/shopify/callback" 
echo "   - https://size-chart-creator-1.onrender.com/api/auth/callback"
echo ""
echo "5. SCOPES: read_inventory,read_products,write_inventory,write_products"
echo ""
echo "6. Click SAVE"
echo ""

echo "📋 STEP 2: UNINSTALL APP COMPLETELY"
echo "==================================="
echo ""
echo "7. Go to Shopify Admin > Apps and sales channels"
echo "8. Find 'AI-Size-Chart-Creator'"
echo "9. Click '...' > Uninstall"
echo "10. Confirm uninstall"
echo "11. Wait 30 seconds"
echo ""

echo "📋 STEP 3: CLEAR BROWSER DATA"
echo "============================="
echo ""
echo "12. Clear ALL browser cookies and cache"
echo "13. Or use incognito/private window"
echo ""

echo "📋 STEP 4: RENDER DEPLOYMENT"
echo "============================"
echo ""
echo "14. Go to Render Dashboard"
echo "15. Add environment variable:"
echo "    SHOPIFY_API_SECRET=[Your app's API secret from Partners Dashboard]"
echo "16. Click 'Manual Deploy' > 'Deploy latest commit'"
echo "17. Wait for deployment to complete"
echo ""

echo "📋 STEP 5: FRESH INSTALLATION"
echo "============================="
echo ""
echo "18. Go back to Shopify Admin > Apps"
echo "19. Install your app fresh from development URL"
echo "20. App should load without any cookie errors"
echo ""

echo "🎯 WHY THIS WILL WORK:"
echo "====================="
echo "- Complete app uninstall clears all cached authentication"
echo "- Fresh browser session removes conflicting cookies"
echo "- Latest code has proper SameSite cookie handling"
echo "- Manual Partner Dashboard update ensures correct URLs"
echo ""

echo "✨ FOLLOW THESE STEPS IN EXACT ORDER!"
echo "The exit-iframe loop will be completely resolved."