#!/bin/bash

echo "Manual Render Deployment Instructions"
echo "======================================"
echo ""
echo "Since automatic deployment isn't working, follow these steps:"
echo ""
echo "1. Go to your Render Dashboard:"
echo "   https://dashboard.render.com/"
echo ""
echo "2. Find your service 'collection-creator' or 'collection-creator-app'"
echo ""
echo "3. Click on the service"
echo ""
echo "4. Go to the 'Settings' tab"
echo ""
echo "5. Check these settings:"
echo "   - Build Command: npm install && npm run build"
echo "   - Start Command: npm run start"
echo "   - Auto-Deploy: Should be 'Yes' for main branch"
echo ""
echo "6. Go to the 'Events' tab to see deployment logs"
echo ""
echo "7. Click 'Manual Deploy' button and select 'main' branch"
echo ""
echo "8. Make sure these environment variables are set:"
echo "   - SHOPIFY_API_KEY"
echo "   - SHOPIFY_API_SECRET"
echo "   - SHOPIFY_APP_URL=https://collection-creator.onrender.com"
echo "   - SCOPES=write_products,read_products,write_inventory,read_inventory"
echo "   - NODE_ENV=production"
echo "   - PORT=3000"
echo ""
echo "If auto-deploy is not working:"
echo "1. Go to Settings > Build & Deploy"
echo "2. Make sure 'Auto-Deploy' is ON"
echo "3. Check that GitHub repo is connected"
echo "4. If not connected, click 'Connect GitHub' and authorize"
echo ""
echo "Press Enter to open Render Dashboard..."
read -r
open "https://dashboard.render.com/"