services:
  # Single Combined Shopify Collection Creator App
  - type: web
    name: collection-creator
    runtime: node
    repo: https://github.com/Axnivo/collection-creator
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        value: https://collection-creator.onrender.com
      - key: SCOPES
        value: write_products,read_products,write_inventory,read_inventory
      - key: HOST
        fromService:
          type: web
          name: collection-creator
          property: host
      - key: RENDER
        value: true