# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92c4ac9864bf9013179f4d04be50e0ce"
name = "Axnivo Collections Manager"
application_url = "https://collection-creator.onrender.com"
embedded = true
handle = "axnivo-collections-manager"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_inventory,write_products"

[auth]
redirect_urls = ["https://collection-creator.onrender.com/auth/callback", "https://collection-creator.onrender.com/auth/shopify/callback", "https://collection-creator.onrender.com/api/auth/callback"]

[pos]
embedded = false
